### ISSUE TITLE
CCTweaks support in rewrite

### ISSUE THREAD

**Issue by apemanzilla** [Lignumm/CCEmuX#14]
@SquidDev in case you haven't yet seen it, we're working on a rewrite of CCEmuX (old version was pretty poor coding style, lots of `throws Exception` and whatnot, see the `rewrite` and `rw-emulation` branches) so we need to do the CCTweaks stuff again.

**Comment by SquidDev** [comment]
One thing to consider, as mentioned before, is just ignoring CCTweaks and people can using its bootstrapper to wrap your emulator if people want to.

**Comment by apemanzilla** [comment]
True, but it's a bit more hacky that way.

**Comment by SquidDev** [comment]
Well, it's hack whatever: you end up overriding the classloader. What bits of CCTweaks do you want to use? All of it or just a couple of features?

**Comment by apemanzilla** [comment]
I think the main one we wanted was LuaJC, but things like the debug API are also very useful.

**Comment by Lignumm** [comment]
Yep, mainly its additions to LuaJ, which includes LuaJC, Cobalt, debug and socket (and bignumber) APIs. The physical stuff like wireless bridges is something we could consider for later when we add peripheral support, though.

**Comment by SquidDev** [comment]
Ok, basically all of CCTweaks-Lua. I didn't know if you only wanted to include LuaJC like before. I'll have to think about a way to configure all of this: currently it uses command line flags which are not the most friendly of ways.

**Comment by apemanzilla** [comment]
We would probably set it up in a way so that either the CCTweaks classes are included in the CCEmuX jar or added to the classpath, and users can enable it in the CCEmuX options.

The flow would be something like `CCEmuX launched -> load CC -> load CCTweaks -> start emulating`, instead of `CCTweaks launched -> ...`
