### ISSUE TITLE
Great Refactoring

### ISSUE THREAD

**Issue by apemanzilla** [Lignumm/CCEmuX#16]
- [x] Move `main` out of `CCEmuX`
- [x] Fix save location
- ~~Attempt to fix `ClasspathMount`~~
- [ ] General cleanup and optimizations
- [ ] Boot shutdown computers when pressing a key

**Comment by Lignumm** [comment]
tbh classpathmount is fucked we shoudl eject it from the project like the UK from the EU

**Comment by apemanzilla** [comment]
`ClasspathMount`xit

**Comment by Lignumm** [comment]
fking christ i tried to lower the intellect but you just wrecked it. Either way, this could be a PR for rw-refactoring.

**Comment by Lemmmy** [comment]
rewrite is a good visual novel
