### ISSUE TITLE
os.clock() milli/nanosecond precision

### ISSUE THREAD

**Issue by ardera** [Lignumm/CCEmuX#21]
It'd be cool if there was a settings point that enables os.clock() to return the time in milli/nanosecond precision. That'd be useful for profiling.

**Comment by Lignumm** [comment]
Wouldn't it make more sense to have `ccemux.getMilliseconds()`?

**Comment by Lignumm** [comment]
Alright, I've added `ccemux.getUnixTime` and `ccemux.getMilliseconds`, which are synonymous in 6ca35390ab0e8a397bb048c15b698221b21bb78b. Do you really need `os.clock()` to be overridden? Even if it's a setting, I'm not sure how well that would work out.

**Comment by ardera** [comment]
Thanks
No you don't need to overwrite os.clock(), an extra function for it is completely ok.

**Comment by SquidDev** [comment]
Just FYI CCTweaks also adds a `profiler.milliTime`/`profiler.nanoTime`. Would it be possible to use the same naming conventions? - then I can do `ccemux or profiler`.

**Comment by Lignumm** [comment]
@SquidDev Sure! Here you go: fa38be739bef1ce04eb2ef1eb33dc3d166e0aab5.
