### ISSUE TITLE
abcdefghijklmnoqprstuvewa

### ISSUE THREAD

**Issue by Lemmmy** [Lignumm/CCEmuX#4]
![](http://itchy.lemmmy.pw/poopy.png)

**Comment by justync7** [comment]
`abcdefghijklmnopqrstuvwxyz` should be the fixed version. you forgot how to alphabet

**Comment by Lemmmy** [comment]
no id idnt fuck you im know how to spell i hate you

**Comment by justync7** [comment]
http://i.imgur.com/8z01Oui.jpg

**Comment by justync7** [comment]
thanks 3d6 very productive

**Comment by lurquhar1221** [comment]
meme
