### ISSUE TITLE
http.get fails to retrieve latest data.

### ISSUE THREAD

**Issue by PyuuCH** [Lignumm/CCEmuX#47]
Using http.get on github's raw githubusercontent site, I found that http.get almost never retrieves the latest data. Using the web browser to access the file (or in this case: https://raw.githubusercontent.com/PyuuCH/CC-plip/v2/plip.lua ), the web browser returns the latest data, but http.get returns an older version of it, making development using github very frustrating.

Since the web browser retrieves the latest data, but the emulator fails to, I can presume there is something wrong with the way the emulator is doing http, or ComputerCraft is at fault. I cannot test ComputerCraft in Minecraft so I can't even tell.

And no, I doubt this is an issue with github itself.

**Comment by Lemmmy** [comment]
Caching problem.

**Comment by SquidDev** [comment]
This would be a vanilla CC problem which CCEmuX is unable to fix. As CC's HTTP implementation doesn't do anything weird I would presume this *is* a GitHub issue due to caching. Changing the `User-Agent` to a fake a browser might help, though I haven't tested.

**Comment by Lemmmy** [comment]
Alternatively, attach a cache buster on the URL. E.g. `http://your.site/your.resource?time=123.45` where 123.45 is `os.clock()` or any other value that is never the same.

**Comment by PyuuCH** [comment]
Just for reference for anyone else who runs across the same problem I do with githubusercontent in specific. You can use the cache buster as Lemmmy described and it will work (as far as I've tested.) Just `?time=math.random()` would work better as advised by him.

**Comment by justync7** [comment]
Alternatively, instead of ?time use a # at the end of your URL and your
preferred cache buster, whether it be a random number or the current time.
This prevents it from interfering with GET parameters.

**Comment by Lemmmy** [comment]
Time is clientside - it wouldn't affect serverside caching (which was the problem here)

**Comment by justync7** [comment]
Ah. My mistake then!

**Comment by Lemmmy** [comment]
is ok
