### ISSUE TITLE
Colours don't change when the screen is scrolled if the character is the same

### ISSUE THREAD

**Issue by Lemmmy** [Lignumm/CCEmuX#5]
When the screen is scrolled, if the character is the same as it was before, its colour will not change.

![](http://incredibly.shitty.download/suite_super_stupid_wanking.gif)

**Comment by justync7** [comment]
you're an 11 on the retard scale drew

**Comment by Lemmmy** [comment]
im sorry

**Comment by justync7** [comment]
and also this bug is confusing me

**Comment by Lemmmy** [comment]
that kind of hurt justyn

**Comment by justync7** [comment]
don't worry it's out of 100

**Comment by Lignumm** [comment]
Ugh fuck!!!
