### ISSUE TITLE
Better Screen Renderer

### ISSUE THREAD

**Issue by CrazedProgrammer** [Lignumm/CCEmuX#54]
The current renderer is very CPU-heavy and slow.
I think there's a better way to do this.
For example: having an off-screen render target and only draw to that target when a term function is called.
When you need to render the final image, you just copy the render target, instead of, well, this https://github.com/Lignumm/CCEmuX/blob/master/src/main/java/net/clgd/ccemux/rendering/awt/TerminalComponent.java#L93

**Comment by apemanzilla** [comment]
See #52
