### ISSUE TITLE
os.clock() lags behind

### ISSUE THREAD

**Issue by CrazedProgrammer** [Lignumm/CCEmuX#56]
When doing intensive computations (not yielding for a couple seconds), os.clock() starts lagging behind ccemux.nanoTime().
It looks like time is slowing down, yet ccemux.nanoTime() keeps being correct.

**Comment by apemanzilla** [comment]
I believe this is an issue on CC's part but I'll look into it.

**Comment by apemanzilla** [comment]
@CrazedProgrammer can you re-test from the latest code on the `plugins` branch?
