### ISSUE TITLE
mouse_drag events being fired too often

### ISSUE THREAD

**Issue by CrazedProgrammer** [Lignumm/CCEmuX#57]
mouse_drag events are being fired not only when the mouse is dragged from one to another cell, it's being fired every pixel.
This means that on a 1000hz mouse, the mouse_drag event gets called up to 1000 times per second, which is a waste.
This happens in the in-dev lwjgl renderer too.

**Comment by apemanzilla** [comment]
Fixed in `a428706ae17adf2e7d7027ca52fe473eb05cfbd0`
