### ISSUE TITLE
File gone blank when running

### ISSUE THREAD

**Issue by CoolMan119** [Lignumm/CCEmuX#60]
When I ran my `player.lua` file it did nothing and the file was blank. It originally had stuff in it but it gone blank for some reason. Please help!

**Comment by CrazedProgrammer** [comment]
I'm pretty sure it's not CCEmuX's fault.

**Comment by apemanzilla** [comment]
If you can provide some source code and clear steps to reproduce the issue I'll look into it, otherwise I'm closing this for now.
