### ISSUE TITLE
Rewrite everything

### ISSUE THREAD

**Issue by apemanzilla** [Lignumm/CCEmuX#8]
lol shit's fucked

**Comment by Lemmmy** [comment]
:ok_hand:

**Comment by demhydraz** [comment]
:ok_hand: :+1:

**Comment by BTCTaras** [comment]
:ok_hand: :+1: :raised_hands:

**Comment by Lignumm** [comment]
shit's still fucked

**Comment by apemanzilla** [comment]
i'm working on it slowly

**Comment by Lignumm** [comment]
maybe we should start a kickstarter to fund this issue

**Comment by BTCTaras** [comment]
ill pledge 8 KST

**Comment by justync7** [comment]
It has come to Krist bounties. Great.

**Comment by BTCTaras** [comment]
ill up it to 10 KST

**Comment by apemanzilla** [comment]
make it 20 and you have a deal

**Comment by BTCTaras** [comment]
15 :grey_question: :question: :grey_question: :question: :grey_question: :question: :grey_question: :question:

**Comment by apemanzilla** [comment]
21

**Comment by Lemmmy** [comment]
what the fuck is wrong with you guys

**Comment by apemanzilla** [comment]
idk ask taras

**Comment by BTCTaras** [comment]
ok deal 21

**Comment by Lignumm** [comment]
i bid 100KST

**Comment by Lignumm** [comment]
i raise 200KST

**Comment by apemanzilla** [comment]
i'm trying but the code also needs to be changed

**Comment by Lemmmy** [comment]
why are you all mentally challenged

**Comment by justync7** [comment]
i am mentally challenged please give me money

**Comment by Lemmmy** [comment]
thats gonna be a bit difficult tbh ![](http://mostly.a.shitty.download/flour_furnished_le.png)

**Comment by BTCTaras** [comment]
ill call 200 KST

**Comment by Lignumm** [comment]
i already did u fag, calling 300 KST

**Comment by Lignumm** [comment]
is it fixed yet

**Comment by BTCTaras** [comment]
calling another 100 KST so i have 300 in the pot now

flop is 6 of hearts, 10 of spades, jack of hearts

**Comment by Lemmmy** [comment]
i want to cry myself to death

**Comment by BTCTaras** [comment]
better change the name to CCEmuWrecks because this place getting destroyed

**Comment by apemanzilla** [comment]
i got this

**Comment by apemanzilla** [comment]
rewrite's going well it's getting better

**Comment by Lemmmy** [comment]
rewrite was a good vn

**Comment by demhydraz** [comment]
fucking finally

**Comment by CrazedProgrammer** [comment]
it a good
